Repository fga-eps-mds/2023.1-CanvLight-Canvas-Inteligente, pull requests merged in 2023-06, with the labels that each got.

#53 Página do tutorial inserida
  package-lock.json
  package.json
  src/index.js
  src/pages/canvas/Canvas.css
  src/pages/canvas/Canvas.js
  src/pages/home/Home.js
  src/pages/tutorial/Tutorial.js
  src/pages/tutorial/tutorial.css
Labels: enhancement, FrontEnd

#60 Organizar no css e na responsividade das páginas
  src/components/GeradorPDF/GeradorPDF.js
  src/components/Interacao/Interacao.css
  src/components/Interacao/Interacao.js
  src/components/intuicao/Intuicao.css
  src/components/intuicao/Intuicao.js
  src/pages/canvas/Canvas.css
  src/pages/canvas/Canvas.js
  src/pages/home/Home.css
  src/pages/tutorial/Tutorial.js
  src/pages/tutorial/tutorial.css
Labels: Arquitetura, FrontEnd

#65 Pdf
  package-lock.json
  package.json
  src/components/GeradorPDF/GeradorPDF.js
  src/components/observacao/Observacao2.js
  src/images/Interacao1.png
  src/images/Interacao2.png
  src/images/Interacao3.png
  src/images/Intuicao.png
  src/images/observacao1.png
  src/images/observacao2.png
  src/images/obvervacao3.png
Labels: pesadelo, FrontEnd
