Repository fga-eps-mds/2023.1-CanvLight-Canvas-Inteligente, pull requests merged in 2023-07, with the labels that each got.

#69 Tornando parte do css responsivo
  src/components/Interacao/Interacao.css
  src/components/intuicao/Intuicao.css
  src/components/intuicao/Intuicao.js
  src/components/observacao/Observacao1.css
  src/components/observacao/Observacao1.js
  src/components/observacao/Observacao2.css
  src/components/observacao/Observacao2.js
  src/components/observacao/Observacao3.css
  src/images/check.png
  src/images/remedio.png
  src/pages/canvas/Canvas.css
  src/pages/canvas/Canvas.js
  src/pages/home/Home.css
  src/pages/tutorial/Tutorial.js
  src/pages/tutorial/tutorial.css
Labels: FrontEnd

#70 Pdf
  src/components/GeradorPDF/GeradorPDF.js
  src/images/Interacao1.png
  src/images/Interacao2.png
  src/images/Interacao3.png
  src/images/Intuicao.png
  src/images/Observacao1.png
  src/images/Observacao2.png
  src/images/Observacao3.png
  src/images/observacao1.png
  src/images/observacao2.png
  src/images/obvervacao3.png
Labels: FrontEnd

#71 Implementa a métrica de maturidade
  package-lock.json
  package.json
  src/components/GeradorPDF/GeradorPDF.js
  src/components/Maturidade/Maturidade1.css
  src/components/Maturidade/Maturidade1.js
  src/components/Maturidade/Maturidade2.css
  src/components/Maturidade/Maturidade2.js
  src/components/Maturidade/Maturidade3.css
  src/components/Maturidade/Maturidade3.js
  src/components/Maturidade/Maturidade4.css
  src/components/Maturidade/Maturidade4.js
  src/components/Maturidade/Maturidade5.css
  src/components/Maturidade/Maturidade5.js
  src/components/Maturidade/descricao1.json
  src/components/Maturidade/descricao2.json
  src/components/Maturidade/descricao3.json
  src/components/Maturidade/descricao4.json
  src/components/Maturidade/descricao5.json
  src/images/situacao1.png
  src/images/situacao2.png
  src/images/situacao3.png
  src/images/situacao4.png
  src/images/situacao5.png
  src/pages/canvas/Canvas.css
  src/pages/canvas/Canvas.js
Labels: difícil, FrontEnd

#77 Arruma todolist
  src/components/Interacao/Interacao.css
  src/components/Interacao/Interacao.js
  src/pages/canvas/Canvas.js
Labels: bug

#80 Maturidade
  package-lock.json
  package.json
  src/components/GeradorPDF/GeradorPDF.js
  src/components/Maturidade/Maturidade1.css
  src/components/Maturidade/Maturidade1.js
  src/components/Maturidade/Maturidade2.js
  src/components/Maturidade/Maturidade3.js
  src/components/Maturidade/Maturidade4.js
  src/components/Maturidade/Maturidade5/Maturidade5.css
  src/components/Maturidade/Maturidade5/Maturidade5.js
  src/components/Maturidade/Maturidade5/Maturidade5Chart/BarChart.css
  src/components/Maturidade/Maturidade5/Maturidade5Chart/BarChart.js
  src/components/Maturidade/Maturidade5/Maturidade5Chart/DadosDasAreas.js
  src/pages/canvas/Canvas.js
  src/pages/tutorial/Tutorial.js
  src/pages/tutorial/tutorial.css
Labels: difícil
